language: rust
rust:
  - stable
  - beta
sudo: false
cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo clippy
  # if you want the build job to fail when encountering warnings, use
  #- cargo clippy -- -D warnings
  # in order to also check tests and none-default crate features, use
  #- cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
  #- cargo test --all --all-features --release

notifications:
  email:
    on_success: never
